// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDIAUqPQIV-LSyDiTeuGgbEhO1Y0TXLOQ',
    appId: '1:608446180656:web:dc1111313cdc6c2683acf5',
    messagingSenderId: '608446180656',
    projectId: 'workwise-autism',
    authDomain: 'workwise-autism.firebaseapp.com',
    storageBucket: 'workwise-autism.appspot.com',
    measurementId: 'G-VN736FNX43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgEdC3LWqxUa6ZQpYyWhRDwhRiSr6rfjE',
    appId: '1:608446180656:android:29b3d49819e7692a83acf5',
    messagingSenderId: '608446180656',
    projectId: 'workwise-autism',
    storageBucket: 'workwise-autism.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtDogN3JOsSfcHAAk7T_0v7soyX0OO4Dc',
    appId: '1:608446180656:ios:11f41a86495e524783acf5',
    messagingSenderId: '608446180656',
    projectId: 'workwise-autism',
    storageBucket: 'workwise-autism.appspot.com',
    iosClientId: '608446180656-7t95u8rldv2ia8e2cudmmb4hvg3c6r7t.apps.googleusercontent.com',
    iosBundleId: 'com.autismeacademie.workwiseAutism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtDogN3JOsSfcHAAk7T_0v7soyX0OO4Dc',
    appId: '1:608446180656:ios:11f41a86495e524783acf5',
    messagingSenderId: '608446180656',
    projectId: 'workwise-autism',
    storageBucket: 'workwise-autism.appspot.com',
    iosClientId: '608446180656-7t95u8rldv2ia8e2cudmmb4hvg3c6r7t.apps.googleusercontent.com',
    iosBundleId: 'com.autismeacademie.workwiseAutism',
  );
}
